### ISSUE TITLE
New cakephp version, issue with setDefault.

### ISSUE THREAD

**Issue by lpj145** [mixerapi/core#1]
https://github.com/mixerapi/core/blob/a0aa5de1824a2fdffac7c5568f0594d00b893896/src/Model/ModelPropertyFactory.php#L45

Whats up ?! recently i'm working with boolean columns on postgres and face this issue.

![image](https://user-images.githubusercontent.com/11980109/99019849-0eb5e800-253c-11eb-9b11-5878719a00f4.png)

Checking code, default column value need be string to factory model properties.

My solution is, why not cast instead of null operator ?

![image](https://user-images.githubusercontent.com/11980109/99019913-35741e80-253c-11eb-97b7-c8c2ba38a702.png)
Give same result, and not send integer to setDefault value anymore.

**Comment by cnizzardini** [comment]
Makes sense to me.  Want to submit a PR @lpj145? Or have that method accept `?string` instead. Not sure which is better.

**Comment by cnizzardini** [comment]
Will you do a `composer update` on your project and verify that worked.
